### ISSUE TITLE
考不考虑提供预览版 : )

### ISSUE THREAD

**Issue by y1jiong** [USS-Shenzhou/MC-R6mod#2]
#### 我很看好你哦！考不考虑提供预览版？黑镜做得太 amazing 了
> 从B站闻声而来，哈哈

**Comment by USS-Shenzhou** [comment]
如果你指的是现在的0.1.0.dev2，那在[CurseForge](https://www.curseforge.com/minecraft/mc-mods/rainbow6)上可以下载。以后也多数会发在CurseForge上。

**Comment by USS-Shenzhou** [comment]
> #### 我很看好你哦！考不考虑提供预览版？黑镜做得太 amazing 了
> > 从B站闻声而来，哈哈

如果你指的是现在的0.1.0.dev2，那在CurseForge上可以下载。以后也多数会发在CurseForge上。

**Comment by y1jiong** [comment]
要不，挂个链接在 readme.md 上？

**Comment by USS-Shenzhou** [comment]
> 要不，挂个链接在 readme.md 上？

这不是没(lan)空(de)搞(xie)嘛 XD

**Comment by y1jiong** [comment]
那视频的三连，是不是 /斜眼笑

**Comment by USS-Shenzhou** [comment]
> 那视频的三连，是不是 /斜眼笑

马上改
老板大气老板身体健康 XD

**Comment by y1jiong** [comment]
要是我会 Java，我也来帮你了 <_<
```
黑镜的“动画”太棒了！！！
```

**Comment by USS-Shenzhou** [comment]
> 要是我会 Java，我也来帮你了 <_<
> 
> ```
> 黑镜的“动画”太棒了！！！
> ```

我也是才开始学。。

**Comment by y1jiong** [comment]
> > 要是我会 Java，我也来帮你了 <_<
> > ```
> > 黑镜的“动画”太棒了！！！
> > ```
> 
> 我也是才开始学。。

我自己整的 Golang，在玩后端 XD
也在写动态域名解析，搞 mc 服务器 (●'◡'●)

**Comment by USS-Shenzhou** [comment]
> > > 要是我会 Java，我也来帮你了 <_<
> > > ```
> > > 黑镜的“动画”太棒了！！！
> > > ```
> > 
> > 
> > 我也是才开始学。。
> 
> 我自己整的 Golang，在玩后端 XD
> 也在写动态域名解析，搞 mc 服务器 (●'◡'●)

（⊙ｏ⊙）以后开服务器貌似可以用XD

**Comment by y1jiong** [comment]
互帮互助，哈哈哈
